#!/bin/bash

config_dir="/opt/osm/drsk_osm_map_styles/drsk_mapcss_styles/"
kothic_path="/opt/osm/kothic/src/"
config="${1}"
tmp=`mktemp /tmp/XXXXX`

cd ${kothic_path}
echo "start: python komap.py -s ${config_dir}/${config} -c komap.conf > ${tmp}"
python komap.py -s ${config_dir}/${config} -c komap.conf > "${tmp}"

if [ 0 -eq $? ]
then
	echo "Нет ошибок"
	rm "${tmp}"
	exit 0
else
	echo "В конфиге ЕСТЬ ошибки!"
	rm "${tmp}"
	exit 1
fi
