#!/bin/bash

config_dir="/opt/osm/drsk_osm_map_styles/drsk_mapcss_styles/"
tilecache_conf="/etc/tilecache.cfg"
mapnik_configs_dir="/etc/mapnik/tilecache_configs"
mapnik_configs_dir_bak="/etc/mapnik/tilecache_configs.bak"
kothic_path="/opt/osm/kothic/src/"

configs=`find ${config_dir} -type f -iname '*.mapcss' -printf "%f "|sed "s/\.mapcss//g"`
rm -f ${mapnik_configs_dir_bak}/*
cp -r ${mapnik_configs_dir}/* ${mapnik_configs_dir_bak}/

if [ ! -d /etc/tilecache.d -o ! -d ${mapnik_configs_dir} -o ! -d ${mapnik_configs_dir_bak} ]
then
	mkdir /etc/tilecache.d ${mapnik_configs_dir} ${mapnik_configs_dir_bak}
	chown www-data:www-data /etc/tilecache.d
fi

cd ${kothic_path}
for config in $configs
do
echo "python komap.py -s ${config_dir}/${config}.mapcss -c komap.conf > osm.xml"
python komap.py --maxzoom=22 -s ${config_dir}/${config}.mapcss -c komap.conf > osm.xml
echo "upgrade-map-xml osm.xml ${mapnik_configs_dir}/${config}.xml"
upgrade-map-xml osm.xml ${mapnik_configs_dir}/${config}.xml
echo "mkdir /var/tilecache/${config}"
mkdir -p /var/tilecache/${config}
chown www-data:www-data /var/tilecache/${config}

# Формируем часть конфига для tilecache:
echo "
# Конфиг сгенерирован автоматически скриптом $0 на основе конфига mapcss ${config_dir}/${config}.mapcss
[${config}]
type=MapnikLayer
mapfile=${mapnik_configs_dir}/${config}.xml
spherical_mercator=true
tms_type=google
metatile=yes
levels=22

" > /etc/tilecache.d/${config}.cfg 

done

# Пропуск правки конфига tilecache:
#exit 0

# Бэкапим старый конфиг tilecache:
cp /etc/tilecache.cfg /etc/tilecache.cfg_bak

if [ ! -f /etc/tilecache.d/00base.ini ]
then
	cp ${config_dir}/00base.ini /etc/tilecache.d/
fi

# Собираем конфиг:
echo "# Конфиг сгенерирован автоматически скриптом ./convert_mapcss2mapnik2" > ${tilecache_conf}
cat /etc/tilecache.d/00base.ini /etc/tilecache.d/*.cfg >> ${tilecache_conf}

# Перезапуск tilecache (вроде как не нужно, т.к. tilecache - это cgi, вызываемый apache-ем по требованию):
#/etc/init.d/apache2 restart

# Т.к. конфиги обновились, очищаем старые тайлы:
/opt/osm/scripts/tilecache_delete_all_layers_cache.sh

exit 0
